name: Deploy
on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: ğŸ—ï¸ Build Jekyll site 
      run: |
        bundle install
        bundle exec jekyll build

    - name: ğŸš€ Deploy via SSH
      uses: appleboy/scp-action@master
      with:
        host: kfskinpusat.com
        username: kfskinpu
        password: ${{ secrets.DEPLOY_KEY }}
        port: 22
        source: "./_site/*" # Adjust if required
        target: "/test.kfskinpusat.com" # Set to your deployment directory (for example /public_html)
        strip_components: 1 # This ensures that a subdirectory is not created
     
