on:
  push:
    branches: [ main ]
name: Deploy website on push
jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Sync files
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: /
        remote_path: /home/kfskinpu/test.kfskinpusat.com
        remote_host: kfskinpusat.com
        remote_user: kfskinpu
        remote_key: ${{ secrets.DEPLOY_KEY }}
